---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - name: process tasks_review_input
      include_tasks: tasks_review_input.yml

- hosts: "{{ inventory_pattern }}"

  tasks:

    - name: set global facts
      include_tasks: tasks_facts.yml
      run_once: yes

    - name: scan for deployment components
      include_tasks: tasks_scan_components.yml
      run_once: yes

    - name: match deployment targets
      include_tasks: tasks_match_targets.yml
      run_once: yes

    - name: find a way to deploy
      imclude_tasks: tasks_deployment_solution.yml

    - name: process deployment components
      include_tasks: tasks_deploy_components.yml

    - name: notify on finish
      include_tasks: tasks_notify_finish.yml
      when: not((mail_to is undefined) or (mail_to is none) or (mail_to | trim ==''))
